### ISSUE TITLE
RuntimeError: NanoVDB signature not found

### ISSUE THREAD

**Issue by rdesc** [NVIDIA/warp#157]
Hi!

I recently installed warp in a conda env with python 3.7 and can't seem to get some of the example demos working. I get the following error:

````
Warp 1.0.0-beta.5 initialized:
   CUDA support not enabled in this build
   Devices:
     "cpu"    | x86_64
   Kernel cache: /home/rdesc/.cache/warp/1.0.0-beta.5
Traceback (most recent call last):
  File "example_sim_granular_collision_sdf.py", line 163, in <module>
    example = Example(stage_path)
  File "example_sim_granular_collision_sdf.py", line 58, in __init__
    rock_vdb = wp.Volume.load_from_nvdb(rock_file.read())
  File "/home/rdesc/miniconda3/envs/diffsim2/lib/python3.7/site-packages/warp/types.py", line 2736, in load_from_nvdb
    raise RuntimeError("NanoVDB signature not found")
RuntimeError: NanoVDB signature not found
````

**Comment by shi-eric** [comment]
This error usually happens because the assets stored in LFS haven't been downloaded. Try doing a `git lfs pull` and try again. The `CUDA support not enabled in this build` message in your log means that you probably won't be able to run this example since `wp.Volume.load_from_numpy()` requires CUDA.
