### ISSUE TITLE
Warp not able to find its own function

### ISSUE THREAD

**Issue by cadop** [NVIDIA/warp#61]
I have a `@wp.func` that is part of a larger call history.  However, the part that it is failing at is:

```
@wp.func
def calc__force(rr_i: wp.vec3, 
                     ri: float, 
                     vv_i: wp.vec3, 
                     pn_rr: wp.array(dtype=wp.vec3), 
                     pn_vv: wp.array(dtype=wp.vec3), 
                     pn_r: wp.array(dtype=float),
                     ):
    force = wp.zeros_like(rr_i)
```

Resulting in:

(The top part of the error, with warp being properly initialized)
```
Warp initialized:
   Version: 0.3.1
   CUDA device: NVIDIA RTX A4500
   Kernel cache: C:\Users\local user\AppData\Local\NVIDIA Corporation\warp\Cache\0.3.1
Error: Could not find function wp.zeros_like as a built-in or user-defined function. Note that user functions must be annotated with a @wp.func decorator to be called from a kernel. while transforming node <class '_ast.Call'> in func: calc_agent_force at line: 11 col: 12:
        force = wp.zeros_like(rr_i)
```

and then the same function is being mentioned at the bottom of the error 

```
....\lib\site-packages\warp\codegen.py", line 1054, in eval
    raise RuntimeError(f"Could not find function {'.'.join(path)} as a built-in or user-defined function. Note that user functions must be annotated with a @wp.func decorator to be called from a kernel.")        
RuntimeError: Could not find function wp.zeros_like as a built-in or user-defined function. Note that user functions must be annotated with a @wp.func decorator to be called from a kernel.
```

Based on the docs, this should be working.  However, I *assume* there is something _else_ wrong, somewhere, and this error is being incorrectly displayed.

**Comment by mmacklin** [comment]
Hi Mat, yeah, `wp.zeros_like()` is not supposed to be called from kernels as it's only used for array construction and we can't allocate arrays inside kernels.

The message is just saying it can't find that function, or at least it's not a `wp.func` annotated function, which is accurate. There is nothing really special about `zeros_like` since it's just a Python function, I'd rather not put special cases in the error reporting to distinguish it - but let me know if you have a suggestion for how this can be improved. 

You can just use regular `wp.vec3` type construction to create zero-initialized built-in types.
